### ISSUE TITLE
Make post box and button pretty

### ISSUE THREAD

**Issue by chaneberg** [GFUCABAM/statler#105] opened 2015-11-13 02:20 UTC

**Comment by mnijmeh11** [comment] 2015-11-17 15:06
I might have gone a little overboard with css

**Comment by aseebart** [comment] 2015-11-19 05:39
The text box is done but something weird happened with the button. Did we want it to look pretty?

**Comment by mnijmeh11** [comment] 2015-11-20 00:30
I tried to add css to the site and it was not liked by the others....I will give you a style sheet that can be shared by all html documents...

**Comment by aseebart** [comment] 2015-11-20 02:55
Duplicate of issue #112

**Closed as completed by aseebart** 2015-11-20 02:55 UTC
Labels: duplicate, HTML + Javascript
