### ISSUE TITLE
Set up API Test framework

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#22] opened 2015-10-09 02:19 UTC
Does PyCharm have one of these built in? If not, select one.

**Comment by bencdelaney** [comment] 2015-10-09 03:48
This provides an awesome Django testing overview:
https://docs.djangoproject.com/en/1.8/intro/tutorial05/

**Comment by mnijmeh11** [comment] 2015-10-15 00:18
https://vrest.io/plans
vREST is an automated REST API Testing Tool. This extension records HTTP requests and their responses in vREST application.
This extension works as part of the hosted application vREST (http://vrest.io - An Online tool for Automated Testing, Mocking, Automated Recording and Specification of REST / RESTful / HTTP APIs). 

It is a very simple extension, which records the HTTP requests of web application under test and also records their parameters, headers, responses and it will automatically store them as test cases in vREST. It can be configured to filter out HTTP requests according to content type and URL pattern while recording.

More info about vREST
- A simple and intuitive tool to quickly validate your REST APIs.
- Deliver zero defect web applications with very less effort in API testing.
- Works in hosted mode (http://vrest.io)
- No skilled resources required to validate your web application.
- Quickly generate documentation for your API specifications.
- De-couple your frontend development with backend development with easy to use Mock Server
- Ease of maintenance over a span of releases.

**Comment by mnijmeh11** [comment] 2015-10-15 00:20
SoapUI. The Swiss-Army Knife of Testing.
SoapUI is a free and open source cross-platform Functional Testing solution. With an easy-to-use graphical interface, and enterprise-class features, SoapUI allows you to easily and rapidly create and execute automated functional, regression, compliance, and load tests. In a single test environment, SoapUI provides complete test coverage and supports all the standard protocols and technologies. There are simply no limits to what you can do with your tests. Meet SoapUI, the world's most complete testing tool!
API Testing for everyone
SoapUI is designed to bring a simplified and complete testing experience to both technical and non-technical users. The easy-to-use graphical interface makes it simple to work with SOAP and REST-based Web services. For example, in order to create a Load Test, you just right click on a Functional Test and run it as a load test. Or use drag and drop to create any test scenario – simple or complex. And for the more experienced user, SoapUI Pro provides Property Transfer wizards that can automatically transfer properties for selected content, making the creation of complex TestCases or Message Flows easy. For maximal control and flexibility, SoapUI Pro also offers out-of-the-box support for advanced scripting that lets you do virtually anything with your tests. So whether you’re a tester, developer, business analyst, or manager, SoapUI has something for everyone.

**Comment by mnijmeh11** [comment] 2015-10-15 01:09
https://pages.apigee.com/Watch-Demo-Confirmation.html?aliId=68560897

**Comment by mnijmeh11** [comment] 2015-10-15 01:11
http://www.testingtools.com/test-automation/
Automated Web Testing Tools 7 Tools
Automatically testing your web application is a good way to ensure that new versions of your application don't introduce bugs and regressions. Automation of your web application testing also allows your development team to make changes and refactor code with more confident, as they can quickly verify the functionality of the application after every change.
However, actually building automated tests for web applications can be challenging because the user interface of your application might change regularly, because of incompatibilities between browsers and because you usually need to support various server or client platforms. The following tools make it easier to build and execute automated tests for your web application.
Open Source
Selenium
Selenium is a popular automated web testing tool and helps you automate web browsers across different platforms. Selenium has the support of some of the largest browser vendors who have taken steps to make Selenium a native part of their browser.
Open Source
Watir
Watir is a set of Ruby libraries for automating web browsers and allows you to write tests that are easy to read and maintain. Watir drives browsers the same way people do (it clicks links, fills in forms, presses buttons etc.) and also checks results such as whether expected text appears on the page.
Open Source
Windmill
Windmill is a web testing tool designed to help testers automate and debug web applications. It comes with a cross-browser test recorder, JavaScript integration and an interactive shell to automate web browsers.
Commercial
Ranorex
Ranorex allows you to automate your web application testing (among other things) and both record user interactions and play them back to execute your tests. Ranorex is one of the more popular commercial tools to build and run automated web and GUI tests.
Open Source
SoapUI
SoapUI is a cross-platform functional testing tool. It has been specifically designed to help automatically test APIs such as SOAP and REST interfaces to ensure the interoperability of different applications.
Open Source
Sahi
Sahi is a tool for automation of web application testing. Sahi is available as a free open source edition as well as a commercial Pro edition.
Commercial
Tellurium
Tellurium is a web automation tool that allows you to design and write your automated tests using plain English without any scripting or programming experience.

**Comment by mnijmeh11** [comment] 2015-10-15 01:13
Automated Testing Cloud Services
Cloud testing services allow you to run your automated web, mobile and unit tests in different environments and on multiple machines without having to build your own testing infrastructure. The below list of services provides a good overview of popular online Selenium and continuous integration services that are easy and affordable to use.
Service Type    Description Pricing
Sauce Labs  Selenium & Mobile   Cross-browser Selenium & mobile testing Starting @ $149/month
TestingBot  Selenium    Cross-browser Selenium testing  Starting @ $40/month
Gridlastic  Selenium    Cross-browser Selenium testing  Starting @ Free
CircleCI    Continuous Integration  Continuous integration service & unit testing   Starting @ $19/month
Tddium  Continuous Integration  Continuous integration service & unit testing   Starting @ $15/month
CloudBees   Continuous Integration  Continuous integration service & unit testing   Starting @ Free
Mailosaur   Email Testing   Service to integrate emails in automated tests  Starting @ Free

**Comment by mnijmeh11** [comment] 2015-10-15 01:13
it might work if I can get it for free....
https://pages.apigee.com/Watch-Demo-Confirmation.html?aliId=68560897

**Comment by bencdelaney** [comment] 2015-10-15 01:30
I appreciate the research, Moses. Are you seeing a frontrunner, framework-wise? It would be awesome if we could pick one and have a basic setup in place by tomorrow night.

**Comment by mnijmeh11** [comment] 2015-10-15 02:05
The soup for json and another one for the html rest and soap...

-----Original Message-----

**Comment by mnijmeh11** [comment] 2015-10-26 19:07
going to setup a wiki on how to test each part with chrome plugins so that everyone can do it with their broswer

closing it and opening API Testing WIKI

**Closed as completed by mnijmeh11** 2015-10-26 19:07 UTC
Labels: Quality / system testing
